-- ============================================================================
-- PAWN — CUSTOMERS + INVENTORY MIGRATION (Phase 1)
-- File:    patches/0003-customers-inventory.sql
-- Date:    2026-04-26
-- Purpose: Customer + inventory schema, sub-records (ID docs, signatures,
--          photos, stones), inventory transfers between sibling shops, and
--          Storage buckets + RLS for the two private file surfaces.
--
-- Apply to: project kjyaxfwlggxiqijiiuna AFTER 0001-foundation.sql and
--           0002-fix-create-tenant-ambiguous-column.sql have already run.
--           Append-only — never edit prior migrations.
--
-- Design notes:
--   - tenant_counters: per-tenant, per-name monotonic counter table. Used
--     by inventory SKUs now; pawn ticket numbers, sale receipt numbers,
--     and repair ticket numbers will reuse it in later phases.
--   - customers and inventory_items are tenant-scoped with deleted_at
--     soft-delete. NEVER hard-delete a customer row that has any linked
--     loans / repairs / sales (gated at app layer).
--   - inventory_items.sku is generated by a BEFORE INSERT trigger when
--     not provided. Format: 'INV-000001' padded to 6 digits, per-tenant
--     monotonic. The integer is also stored separately for sortable lists.
--   - inventory_transfers: only allowed between sibling shops in the same
--     chain (same parent_tenant_id). Cross-chain transfers blocked by
--     trigger. Standalone tenants cannot use transfers at all.
--   - Storage layout: every uploaded file's path starts with the tenant_id
--     UUID as the first folder segment. RLS policies on storage.objects
--     extract that segment and filter via my_accessible_tenant_ids().
--   - Money: numeric(18,4). Metal weights: numeric(10,4) grams.
--     Stone carat: numeric(10,4). Tax/interest rates: numeric(6,4).
-- ============================================================================

-- ───────────────────────────────────────────────────────────────────────────
--  ENUMS
-- ───────────────────────────────────────────────────────────────────────────

DO $$ BEGIN
  CREATE TYPE id_document_type AS ENUM (
    'drivers_license',
    'state_id',
    'passport',
    'military_id',
    'permanent_resident_card',
    'other'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE customer_doc_kind AS ENUM (
    'id_scan',          -- photo/scan of the customer's ID
    'signature'         -- signature on file (capture pad or upload)
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE comm_preference AS ENUM (
    'email',
    'sms',
    'whatsapp',
    'none'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE inventory_category AS ENUM (
    'ring',
    'necklace',
    'bracelet',
    'earrings',
    'pendant',
    'chain',
    'watch',
    'coin',
    'bullion',
    'loose_stone',
    'electronics',     -- tools, phones, etc. (pawn shops accept these too)
    'tool',
    'instrument',
    'other'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE inventory_source AS ENUM (
    'pawn_forfeit',     -- collateral from a defaulted pawn loan
    'bought',           -- buy-outright from a customer
    'consigned',        -- on consignment, not owned by shop
    'new_stock',        -- new merchandise from a vendor
    'repair_excess',    -- leftover material/stones from a repair job
    'abandoned_repair'  -- repair item left unclaimed past abandon period
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE inventory_status AS ENUM (
    'available',        -- on the floor, sellable
    'held',             -- buy-outright hold period or layaway hold
    'sold',
    'scrapped',         -- melted or written off
    'transferred',      -- moved to a sibling shop
    'returned'          -- customer returned a sold item; back in stock pending review
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE metal_type AS ENUM (
    'gold',
    'silver',
    'platinum',
    'palladium',
    'rose_gold',
    'white_gold',
    'tungsten',
    'titanium',
    'stainless_steel',
    'mixed',
    'none',
    'other'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE inventory_location AS ENUM (
    'case',             -- on display in a case
    'safe',             -- in shop safe
    'vault',            -- in main vault
    'display',          -- generic display area / window
    'workshop',         -- with the bench tech
    'offsite',          -- in transit / at appraiser / at lab
    'transfer'          -- pending or in inventory_transfer
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE transfer_status AS ENUM (
    'pending',          -- created, not yet shipped
    'in_transit',
    'received',         -- accepted at destination
    'cancelled'         -- voided before completion
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ───────────────────────────────────────────────────────────────────────────
--  TENANT COUNTERS — generic per-tenant monotonic sequence.
-- ───────────────────────────────────────────────────────────────────────────
-- Used by inventory SKUs in this migration; pawn ticket numbers, sale
-- receipt numbers, repair ticket numbers will reuse it in later phases.
-- Each (tenant_id, counter_name) advances independently.

CREATE TABLE IF NOT EXISTS tenant_counters (
  tenant_id     UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  counter_name  TEXT NOT NULL,
  last_value    BIGINT NOT NULL DEFAULT 0,
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (tenant_id, counter_name)
);

CREATE OR REPLACE FUNCTION next_tenant_counter(
  p_tenant_id     UUID,
  p_counter_name  TEXT
) RETURNS BIGINT
LANGUAGE plpgsql
AS $$
#variable_conflict use_column
DECLARE v_value BIGINT;
BEGIN
  INSERT INTO tenant_counters (tenant_id, counter_name, last_value)
  VALUES (p_tenant_id, p_counter_name, 1)
  ON CONFLICT (tenant_id, counter_name) DO UPDATE
    SET last_value = tenant_counters.last_value + 1,
        updated_at = NOW()
  RETURNING last_value INTO v_value;
  RETURN v_value;
END;
$$;

-- ───────────────────────────────────────────────────────────────────────────
--  CUSTOMERS
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS customers (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id           UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

  -- Identity
  first_name          TEXT NOT NULL,
  last_name           TEXT NOT NULL,
  middle_name         TEXT,
  date_of_birth       DATE,
  photo_url           TEXT,                       -- portrait photo (signed URL only)

  -- Contact
  phone               TEXT,
  phone_alt           TEXT,
  email               TEXT,

  -- Address
  address1            TEXT,
  address2            TEXT,
  city                TEXT,
  state               TEXT,
  zip                 TEXT,
  country             TEXT DEFAULT 'US',

  -- Government ID (current; full history lives in customer_documents)
  id_type             id_document_type,
  id_number           TEXT,
  id_state            TEXT,                       -- issuing state for DL / state ID
  id_country          TEXT DEFAULT 'US',          -- for passport
  id_expiry           DATE,

  -- Communication preferences
  comm_preference     comm_preference NOT NULL DEFAULT 'sms',
  language            TEXT NOT NULL DEFAULT 'en' CHECK (language IN ('en','es')),
  marketing_opt_in    BOOLEAN NOT NULL DEFAULT FALSE,

  -- Banned-list flag (visible in shop, blocks new transactions at app layer)
  is_banned           BOOLEAN NOT NULL DEFAULT FALSE,
  banned_reason       TEXT,
  banned_at           TIMESTAMPTZ,
  banned_by           UUID REFERENCES auth.users(id),

  -- Staff-only operational fields
  notes               TEXT,
  tags                TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- Audit / soft-delete
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at          TIMESTAMPTZ,
  created_by          UUID REFERENCES auth.users(id),
  updated_by          UUID REFERENCES auth.users(id)
);

CREATE INDEX IF NOT EXISTS idx_customers_tenant       ON customers(tenant_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_customers_tenant_name  ON customers(tenant_id, last_name, first_name) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_customers_tenant_phone ON customers(tenant_id, phone) WHERE deleted_at IS NULL AND phone IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_customers_tenant_email ON customers(tenant_id, email) WHERE deleted_at IS NULL AND email IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_customers_tenant_banned ON customers(tenant_id) WHERE is_banned = TRUE AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_customers_tags         ON customers USING GIN(tags);

-- ───────────────────────────────────────────────────────────────────────────
--  CUSTOMER DOCUMENTS — ID scans, signatures. All in private Storage.
-- ───────────────────────────────────────────────────────────────────────────
-- Multiple rows per customer: history of ID scans (renewed DLs), signatures
-- captured on different visits, etc. The "current" one for any kind is the
-- most recent non-deleted row of that kind.

CREATE TABLE IF NOT EXISTS customer_documents (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  customer_id     UUID NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  kind            customer_doc_kind NOT NULL,
  -- Storage path WITHIN the customer-documents bucket. Convention:
  -- '<tenant_id>/<customer_id>/<kind>/<uuid>.<ext>'
  storage_path    TEXT NOT NULL,
  mime_type       TEXT,
  byte_size       BIGINT,
  -- For ID scans: snapshot of the ID metadata at upload time (so it's
  -- preserved even if the live customer.id_* fields are later updated).
  id_type         id_document_type,
  id_number       TEXT,
  id_state        TEXT,
  id_expiry       DATE,
  notes           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by      UUID REFERENCES auth.users(id),
  deleted_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_customer_docs_customer ON customer_documents(customer_id, kind, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_customer_docs_tenant   ON customer_documents(tenant_id) WHERE deleted_at IS NULL;

-- ───────────────────────────────────────────────────────────────────────────
--  INVENTORY ITEMS
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS inventory_items (
  id                  UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id           UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

  -- SKU: per-tenant monotonic. Trigger fills both fields when sku is NULL on
  -- insert. Format: 'INV-000001' (6-digit zero-padded). sku_number is the
  -- raw integer kept for sortable indexes.
  sku                 TEXT NOT NULL,
  sku_number          BIGINT NOT NULL,

  -- Description
  description         TEXT NOT NULL,
  category            inventory_category NOT NULL DEFAULT 'other',
  brand               TEXT,
  model               TEXT,
  serial_number       TEXT,                       -- for watches, electronics

  -- Metal
  metal               metal_type,
  karat               TEXT,                       -- '10K' | '14K' | '18K' | '24K' | '925' | etc.
  weight_grams        NUMERIC(10,4),
  weight_dwt          NUMERIC(10,4),              -- pennyweight (gold/silver trade unit)

  -- Pricing
  cost_basis          NUMERIC(18,4) NOT NULL DEFAULT 0,  -- what we paid / our basis
  list_price          NUMERIC(18,4),                     -- sticker
  sale_price          NUMERIC(18,4),                     -- realized sale (set on sale)
  sold_at             TIMESTAMPTZ,

  -- Sourcing
  source              inventory_source NOT NULL,
  source_loan_id      UUID,                       -- forfeitures: FK to loans (loans table lands Phase 2; FK added later)
  source_repair_id    UUID,                       -- repair_excess / abandoned_repair (FK added Phase 3)
  source_vendor       TEXT,                       -- new_stock / consigned: vendor name
  acquired_at         DATE NOT NULL DEFAULT CURRENT_DATE,
  acquired_cost       NUMERIC(18,4),              -- what we paid the source

  -- Buy-outright hold tracking
  hold_until          DATE,                       -- if status='held' for buy-hold period
  released_from_hold_at TIMESTAMPTZ,

  -- Location + status
  location            inventory_location NOT NULL DEFAULT 'case',
  status              inventory_status NOT NULL DEFAULT 'available',

  -- Free-form
  notes               TEXT,
  staff_memo          TEXT,                       -- internal-only, never on customer-facing surfaces
  tags                TEXT[] DEFAULT ARRAY[]::TEXT[],

  -- Audit / soft-delete
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at          TIMESTAMPTZ,
  created_by          UUID REFERENCES auth.users(id),
  updated_by          UUID REFERENCES auth.users(id),

  UNIQUE(tenant_id, sku)
);

CREATE INDEX IF NOT EXISTS idx_inventory_tenant         ON inventory_items(tenant_id) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_tenant_status  ON inventory_items(tenant_id, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_tenant_category ON inventory_items(tenant_id, category) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_tenant_source  ON inventory_items(tenant_id, source) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_sku_number     ON inventory_items(tenant_id, sku_number DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_serial         ON inventory_items(tenant_id, serial_number) WHERE serial_number IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_hold_until     ON inventory_items(tenant_id, hold_until) WHERE status = 'held' AND deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_tags           ON inventory_items USING GIN(tags);

-- BEFORE INSERT trigger to assign SKU when not provided.
CREATE OR REPLACE FUNCTION inventory_items_assign_sku()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.sku IS NULL OR NEW.sku = '' THEN
    NEW.sku_number := next_tenant_counter(NEW.tenant_id, 'inventory_sku');
    NEW.sku := 'INV-' || LPAD(NEW.sku_number::TEXT, 6, '0');
  ELSIF NEW.sku_number IS NULL THEN
    -- App-provided SKU: stash the counter value anyway so sortable order
    -- still works. Don't advance the counter (user-provided SKUs are
    -- expected to live outside the auto-numbered range).
    NEW.sku_number := 0;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_inventory_items_sku ON inventory_items;
CREATE TRIGGER trg_inventory_items_sku
BEFORE INSERT ON inventory_items
FOR EACH ROW EXECUTE FUNCTION inventory_items_assign_sku();

-- ───────────────────────────────────────────────────────────────────────────
--  INVENTORY ITEM PHOTOS — multi-image, ordered.
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS inventory_item_photos (
  id            UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id     UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  item_id       UUID NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  -- Storage path WITHIN the inventory-photos bucket. Convention:
  -- '<tenant_id>/<item_id>/<uuid>.<ext>'
  storage_path  TEXT NOT NULL,
  mime_type     TEXT,
  byte_size     BIGINT,
  -- Display ordering. position 0 = primary.
  position      INTEGER NOT NULL DEFAULT 0,
  is_primary    BOOLEAN NOT NULL DEFAULT FALSE,
  caption       TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by    UUID REFERENCES auth.users(id),
  deleted_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_inventory_photos_item    ON inventory_item_photos(item_id, position) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_photos_tenant  ON inventory_item_photos(tenant_id) WHERE deleted_at IS NULL;

-- Ensure exactly one primary photo per item: trigger demotes others.
CREATE OR REPLACE FUNCTION inventory_photos_one_primary()
RETURNS TRIGGER AS $$
BEGIN
  IF NEW.is_primary = TRUE THEN
    UPDATE inventory_item_photos
       SET is_primary = FALSE
     WHERE item_id = NEW.item_id
       AND id <> NEW.id
       AND is_primary = TRUE;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_inventory_photos_one_primary ON inventory_item_photos;
CREATE TRIGGER trg_inventory_photos_one_primary
AFTER INSERT OR UPDATE OF is_primary ON inventory_item_photos
FOR EACH ROW WHEN (NEW.is_primary = TRUE)
EXECUTE FUNCTION inventory_photos_one_primary();

-- ───────────────────────────────────────────────────────────────────────────
--  INVENTORY ITEM STONES — sub-records for stone-bearing items.
-- ───────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS inventory_item_stones (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  item_id         UUID NOT NULL REFERENCES inventory_items(id) ON DELETE CASCADE,
  -- Quantity for this row (e.g., a halo of 12 melee diamonds = one row, count=12).
  count           INTEGER NOT NULL DEFAULT 1,
  stone_type      TEXT,                  -- 'diamond' | 'sapphire' | 'ruby' | 'emerald' | 'cz' | 'moissanite' | etc.
  cut             TEXT,                  -- 'round' | 'princess' | 'oval' | 'emerald' | 'pear' | etc.
  -- Carat. For multi-stone rows, this is per-stone OR total — disambiguate
  -- via is_total_carat below. Default convention: per-stone.
  carat           NUMERIC(10,4),
  is_total_carat  BOOLEAN NOT NULL DEFAULT FALSE,
  -- GIA-ish grading. Free-text so we don't lock in any single grading scale.
  color           TEXT,                  -- 'D' | 'E' | 'F' | 'G' | etc. (or 'colorless')
  clarity         TEXT,                  -- 'IF' | 'VVS1' | 'VS2' | 'SI1' | etc.
  certificate     TEXT,                  -- e.g., 'GIA #2348923490'
  position        INTEGER NOT NULL DEFAULT 0, -- display ordering
  notes           TEXT,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at      TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_inventory_stones_item   ON inventory_item_stones(item_id, position) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_stones_tenant ON inventory_item_stones(tenant_id) WHERE deleted_at IS NULL;

-- ───────────────────────────────────────────────────────────────────────────
--  INVENTORY TRANSFERS — move items between sibling shops in a chain.
-- ───────────────────────────────────────────────────────────────────────────
-- Cross-chain transfers are blocked at the trigger level. Standalone tenants
-- (no parent_tenant_id) cannot use transfers at all.

CREATE TABLE IF NOT EXISTS inventory_transfers (
  id              UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  -- For RLS: every transfer belongs to its origin tenant. The destination
  -- tenant gets read access via a separate policy (its own siblings list).
  tenant_id       UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,

  from_tenant_id  UUID NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  to_tenant_id    UUID NOT NULL REFERENCES tenants(id) ON DELETE RESTRICT,
  item_id         UUID NOT NULL REFERENCES inventory_items(id) ON DELETE RESTRICT,

  status          transfer_status NOT NULL DEFAULT 'pending',
  shipped_at      TIMESTAMPTZ,
  received_at     TIMESTAMPTZ,
  cancelled_at    TIMESTAMPTZ,

  carrier         TEXT,
  tracking_number TEXT,
  notes           TEXT,

  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by      UUID REFERENCES auth.users(id),
  updated_by      UUID REFERENCES auth.users(id),

  CONSTRAINT inventory_transfers_distinct_tenants CHECK (from_tenant_id <> to_tenant_id),
  CONSTRAINT inventory_transfers_origin_match    CHECK (tenant_id = from_tenant_id)
);

CREATE INDEX IF NOT EXISTS idx_inventory_transfers_from ON inventory_transfers(from_tenant_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_transfers_to   ON inventory_transfers(to_tenant_id,   status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_transfers_item ON inventory_transfers(item_id);

-- Block cross-chain transfers: from and to MUST share the same parent_tenant_id,
-- and that parent must be non-null (i.e., both are children of a chain_hq).
CREATE OR REPLACE FUNCTION inventory_transfers_validate_siblings()
RETURNS TRIGGER AS $$
DECLARE
  v_from_parent UUID;
  v_to_parent   UUID;
BEGIN
  SELECT parent_tenant_id INTO v_from_parent FROM tenants WHERE id = NEW.from_tenant_id;
  SELECT parent_tenant_id INTO v_to_parent   FROM tenants WHERE id = NEW.to_tenant_id;

  IF v_from_parent IS NULL OR v_to_parent IS NULL THEN
    RAISE EXCEPTION 'inventory_transfers requires both shops to belong to a chain (parent_tenant_id NOT NULL).';
  END IF;
  IF v_from_parent <> v_to_parent THEN
    RAISE EXCEPTION 'inventory_transfers blocked: from_tenant and to_tenant must share the same parent_tenant_id (same chain).';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_inventory_transfers_siblings ON inventory_transfers;
CREATE TRIGGER trg_inventory_transfers_siblings
BEFORE INSERT OR UPDATE OF from_tenant_id, to_tenant_id ON inventory_transfers
FOR EACH ROW EXECUTE FUNCTION inventory_transfers_validate_siblings();

-- ───────────────────────────────────────────────────────────────────────────
--  UPDATED_AT TRIGGERS
-- ───────────────────────────────────────────────────────────────────────────
-- update_updated_at() function is already defined in 0001-foundation.sql.

DROP TRIGGER IF EXISTS trg_customers_updated_at ON customers;
CREATE TRIGGER trg_customers_updated_at BEFORE UPDATE ON customers
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_inventory_items_updated_at ON inventory_items;
CREATE TRIGGER trg_inventory_items_updated_at BEFORE UPDATE ON inventory_items
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

DROP TRIGGER IF EXISTS trg_inventory_transfers_updated_at ON inventory_transfers;
CREATE TRIGGER trg_inventory_transfers_updated_at BEFORE UPDATE ON inventory_transfers
FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- ───────────────────────────────────────────────────────────────────────────
--  ROW LEVEL SECURITY — TABLES
-- ───────────────────────────────────────────────────────────────────────────

ALTER TABLE tenant_counters         ENABLE ROW LEVEL SECURITY;
ALTER TABLE customers               ENABLE ROW LEVEL SECURITY;
ALTER TABLE customer_documents      ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_items         ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_item_photos   ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_item_stones   ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_transfers     ENABLE ROW LEVEL SECURITY;

-- ── tenant_counters: staff-readable, app-only writes (RPC).
DROP POLICY IF EXISTS tenant_counters_read ON tenant_counters;
CREATE POLICY tenant_counters_read ON tenant_counters FOR SELECT
  USING (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  );

-- ── customers
DROP POLICY IF EXISTS customers_staff_read ON customers;
CREATE POLICY customers_staff_read ON customers FOR SELECT
  USING (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  );

DROP POLICY IF EXISTS customers_staff_write ON customers;
CREATE POLICY customers_staff_write ON customers FOR ALL
  USING (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  )
  WITH CHECK (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  );

-- ── customer_documents
DROP POLICY IF EXISTS customer_docs_staff_read ON customer_documents;
CREATE POLICY customer_docs_staff_read ON customer_documents FOR SELECT
  USING (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  );

DROP POLICY IF EXISTS customer_docs_staff_write ON customer_documents;
CREATE POLICY customer_docs_staff_write ON customer_documents FOR ALL
  USING (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  )
  WITH CHECK (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  );

-- ── inventory_items (and photos / stones use the same shape)
DROP POLICY IF EXISTS inventory_items_staff_read ON inventory_items;
CREATE POLICY inventory_items_staff_read ON inventory_items FOR SELECT
  USING (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  );

DROP POLICY IF EXISTS inventory_items_staff_write ON inventory_items;
CREATE POLICY inventory_items_staff_write ON inventory_items FOR ALL
  USING (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  )
  WITH CHECK (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  );

DROP POLICY IF EXISTS inventory_photos_staff_read ON inventory_item_photos;
CREATE POLICY inventory_photos_staff_read ON inventory_item_photos FOR SELECT
  USING (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  );

DROP POLICY IF EXISTS inventory_photos_staff_write ON inventory_item_photos;
CREATE POLICY inventory_photos_staff_write ON inventory_item_photos FOR ALL
  USING (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  )
  WITH CHECK (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  );

DROP POLICY IF EXISTS inventory_stones_staff_read ON inventory_item_stones;
CREATE POLICY inventory_stones_staff_read ON inventory_item_stones FOR SELECT
  USING (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  );

DROP POLICY IF EXISTS inventory_stones_staff_write ON inventory_item_stones;
CREATE POLICY inventory_stones_staff_write ON inventory_item_stones FOR ALL
  USING (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  )
  WITH CHECK (
    tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(tenant_id)
  );

-- ── inventory_transfers: BOTH origin and destination shops can see the row.
DROP POLICY IF EXISTS inventory_transfers_read ON inventory_transfers;
CREATE POLICY inventory_transfers_read ON inventory_transfers FOR SELECT
  USING (
    (
      from_tenant_id IN (SELECT my_accessible_tenant_ids())
      AND my_is_staff(from_tenant_id)
    )
    OR
    (
      to_tenant_id IN (SELECT my_accessible_tenant_ids())
      AND my_is_staff(to_tenant_id)
    )
  );

-- Writes scoped to origin tenant only (the destination accepts via an
-- update of status, which goes through a server action with explicit
-- to_tenant staff check at app layer).
DROP POLICY IF EXISTS inventory_transfers_origin_write ON inventory_transfers;
CREATE POLICY inventory_transfers_origin_write ON inventory_transfers FOR ALL
  USING (
    from_tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(from_tenant_id)
  )
  WITH CHECK (
    from_tenant_id IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff(from_tenant_id)
  );

-- ───────────────────────────────────────────────────────────────────────────
--  STORAGE BUCKETS — private; signed URL only.
-- ───────────────────────────────────────────────────────────────────────────
-- Path convention (enforced at app layer, RLS verifies):
--   customer-documents/<tenant_id>/<customer_id>/<kind>/<uuid>.<ext>
--   inventory-photos/<tenant_id>/<item_id>/<uuid>.<ext>

INSERT INTO storage.buckets (id, name, public)
VALUES ('customer-documents', 'customer-documents', FALSE)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public)
VALUES ('inventory-photos', 'inventory-photos', FALSE)
ON CONFLICT (id) DO NOTHING;

-- ── customer-documents: staff-only read/write within accessible tenants.
DROP POLICY IF EXISTS customer_docs_storage_read ON storage.objects;
CREATE POLICY customer_docs_storage_read ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'customer-documents'
    AND (
      SELECT (storage.foldername(name))[1]::UUID
    ) IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff((SELECT (storage.foldername(name))[1]::UUID))
  );

DROP POLICY IF EXISTS customer_docs_storage_write ON storage.objects;
CREATE POLICY customer_docs_storage_write ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'customer-documents'
    AND (
      SELECT (storage.foldername(name))[1]::UUID
    ) IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff((SELECT (storage.foldername(name))[1]::UUID))
  );

DROP POLICY IF EXISTS customer_docs_storage_update ON storage.objects;
CREATE POLICY customer_docs_storage_update ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'customer-documents'
    AND (
      SELECT (storage.foldername(name))[1]::UUID
    ) IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff((SELECT (storage.foldername(name))[1]::UUID))
  );

DROP POLICY IF EXISTS customer_docs_storage_delete ON storage.objects;
CREATE POLICY customer_docs_storage_delete ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'customer-documents'
    AND (
      SELECT (storage.foldername(name))[1]::UUID
    ) IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff((SELECT (storage.foldername(name))[1]::UUID))
  );

-- ── inventory-photos: staff-only read/write within accessible tenants.
DROP POLICY IF EXISTS inventory_photos_storage_read ON storage.objects;
CREATE POLICY inventory_photos_storage_read ON storage.objects FOR SELECT
  TO authenticated
  USING (
    bucket_id = 'inventory-photos'
    AND (
      SELECT (storage.foldername(name))[1]::UUID
    ) IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff((SELECT (storage.foldername(name))[1]::UUID))
  );

DROP POLICY IF EXISTS inventory_photos_storage_write ON storage.objects;
CREATE POLICY inventory_photos_storage_write ON storage.objects FOR INSERT
  TO authenticated
  WITH CHECK (
    bucket_id = 'inventory-photos'
    AND (
      SELECT (storage.foldername(name))[1]::UUID
    ) IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff((SELECT (storage.foldername(name))[1]::UUID))
  );

DROP POLICY IF EXISTS inventory_photos_storage_update ON storage.objects;
CREATE POLICY inventory_photos_storage_update ON storage.objects FOR UPDATE
  TO authenticated
  USING (
    bucket_id = 'inventory-photos'
    AND (
      SELECT (storage.foldername(name))[1]::UUID
    ) IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff((SELECT (storage.foldername(name))[1]::UUID))
  );

DROP POLICY IF EXISTS inventory_photos_storage_delete ON storage.objects;
CREATE POLICY inventory_photos_storage_delete ON storage.objects FOR DELETE
  TO authenticated
  USING (
    bucket_id = 'inventory-photos'
    AND (
      SELECT (storage.foldername(name))[1]::UUID
    ) IN (SELECT my_accessible_tenant_ids())
    AND my_is_staff((SELECT (storage.foldername(name))[1]::UUID))
  );

-- Reload PostgREST schema cache.
NOTIFY pgrst, 'reload schema';

-- ============================================================================
-- END 0003-customers-inventory.sql
-- ============================================================================
